import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { buildClaimTracker, buildMobileData, forecastBucket, normalizeRevenueItem } from "../src/lib/spear-mobile.ts";

const now = new Date("2026-08-16T12:00:00.000Z");
const base = { id: "case-1", order_id: "order-1", patient_name: "Real Patient", dob: "1980-01-01", payer: "UHC", member_id: "m", provider: "Provider", npi: "1", hcpcs: ["E0114"], icd: ["M25.5"], product: "Brace", laterality: "R", order_date: "2026-08-01", status: "ready_to_bill", billing_status: "ready", trident_status: "complete", pod_status: "signed", tebra_status: "", missing_fields: [], high_risk_flags: [], created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-16T00:00:00Z", source: "production" };

test("collectible forecast never defaults to billed charges", () => { const item = normalizeRevenueItem({ ...base, billed_amount: 1200 }, now); assert.equal(item.expectedCollectibleAmount, null); assert.equal(item.forecastMethod, "UNKNOWN"); });
test("835 adjudication overrides other forecast bases", () => { const item = normalizeRevenueItem({ ...base, adjudicated_amount: 700, payer_allowable: 800, contracted_rate: 900 }, now); assert.equal(item.expectedCollectibleAmount, 700); assert.equal(item.forecastMethod, "ADJUDICATED_835"); });
test("forecast buckets use expected payment date", () => { assert.equal(forecastBucket("2026-08-23T12:00:00Z", now), "NEXT_7_DAYS"); assert.equal(forecastBucket("2026-09-20T12:00:00Z", now), "DAYS_31_60"); assert.equal(forecastBucket(null, now), "UNSCHEDULED"); });
test("dashboard math and actions derive from persisted fields", () => { const data = buildMobileData([{ ...base, submitted_amount: 1000, payer_allowable: 600, paid_amount: 200, outstanding_amount: 400, expected_payment_date: "2026-08-20T12:00:00Z", eligibility_status: "verified", authorization_status: "NO_AUTH_REQUIRED_VERIFIED" }], now); assert.deepEqual(data.kpis, { revenueSubmitted: 1000, expectedRevenue: 600, collected: 200, arOutstanding: 400 }); assert.equal(data.actionCounts.READY_TO_BILL, 1); assert.equal(data.buckets.find(row => row.key === "NEXT_7_DAYS").expectedCash, 600); });
test("deadline risk sorts before otherwise equal actions", () => { const data = buildMobileData([{ ...base, id: "late", status: "ready_to_bill", payer_allowable: 500 }, { ...base, id: "deadline", status: "closed", claim_status: "denied", denial_reason: "CO-50", payer_allowable: 500, appeal_deadline: "2026-08-17T12:00:00Z" }], now); assert.equal(data.actions[0].caseId, "deadline"); });
test("claim tracker maps operational milestones to rep-friendly colors", () => { const tracker = buildClaimTracker({ ...base, fax_status: "SENT", swo_status: "SIGNED", notes: "Called office", authorization_status: "APPROVED", claim_status: "SUBMITTED", pod_status: "signature_required" }); assert.equal(tracker.find(row => row.key === "sent").status, "complete"); assert.equal(tracker.find(row => row.key === "authorization").status, "complete"); assert.equal(tracker.find(row => row.key === "shipped").status, "pending"); });
test("service worker excludes APIs and PHI-bearing authenticated requests", async () => { const source = await readFile(new URL("../public/spear-sw.js", import.meta.url), "utf8"); assert.match(source, /pathname\.startsWith\("\/api\/"\)/); assert.match(source, /headers\.has\("authorization"\)/); assert.match(source, /headers\.has\("cookie"\)/); });
test("manifest is standalone and starts at mobile command", async () => { const source = await readFile(new URL("../src/app/manifest.ts", import.meta.url), "utf8"); assert.match(source, /start_url: "\/spear\/mobile"/); assert.match(source, /display: "standalone"/); });
