#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_DIR="${ROOT_DIR}/frontend"
RUN_DEV=0

if [[ "${1:-}" == "--dev" ]]; then
  RUN_DEV=1
fi

if [[ ! -d "${FRONTEND_DIR}" ]]; then
  echo "frontend/ directory not found at ${FRONTEND_DIR}" >&2
  exit 1
fi

echo "POSEIDON fix: resetting frontend at ${FRONTEND_DIR}"

rm -rf "${FRONTEND_DIR}/.next"
rm -rf "${FRONTEND_DIR}/node_modules"
rm -rf "${FRONTEND_DIR}/.turbo"
rm -f "${FRONTEND_DIR}/package-lock.json"
rm -f "${FRONTEND_DIR}/yarn.lock"
rm -f "${FRONTEND_DIR}/pnpm-lock.yaml"
rm -rf "${FRONTEND_DIR}/tsconfig.tsbuildinfo"
rm -rf "${FRONTEND_DIR}/.swc"

mkdir -p "${FRONTEND_DIR}/src/app"

cat > "${FRONTEND_DIR}/next.config.js" <<'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}

module.exports = nextConfig
EOF

cat > "${FRONTEND_DIR}/tsconfig.json" <<'EOF'
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

cat > "${FRONTEND_DIR}/tailwind.config.ts" <<'EOF'
import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "sans-serif"],
        mono: ["DM Mono", "monospace"],
        display: ["Bebas Neue", "Impact", "sans-serif"],
      },
      colors: {
        navy: "#05080f",
        "navy-2": "#0a0e1a",
        "navy-3": "#0f1525",
        "navy-4": "#151c30",
        "accent-blue": "#1a6ef5",
        "accent-gold": "#c9921a",
        "accent-gold-2": "#f0b432",
        "accent-green": "#0fa86a",
        "accent-red": "#e03a3a",
        "accent-amber": "#d4820f",
        "accent-purple": "#7c5af0",
        "accent-teal": "#0d9eaa",
      },
    },
  },
  plugins: [],
}

export default config
EOF

cat > "${FRONTEND_DIR}/postcss.config.js" <<'EOF'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
EOF

cat > "${FRONTEND_DIR}/package.json" <<'EOF'
{
  "name": "poseidon-frontend",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.4.5"
  }
}
EOF

cat > "${FRONTEND_DIR}/next-env.d.ts" <<'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js and should not be edited.
EOF

cat > "${FRONTEND_DIR}/src/app/layout.tsx" <<'EOF'
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Poseidon OS — StrykeFox Medical",
  description: "Clinical operations platform",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
EOF

cat > "${FRONTEND_DIR}/src/app/globals.css" <<'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;

@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&family=DM+Mono:wght@300;400&display=swap');

*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  scroll-behavior: smooth;
}

body {
  background: #05080f;
  color: #c8dff5;
  font-family: 'DM Sans', sans-serif;
  font-size: 13px;
  overflow-x: hidden;
}

::-webkit-scrollbar { width: 4px; height: 4px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: rgba(40,90,180,0.32); border-radius: 4px; }
EOF

cat > "${FRONTEND_DIR}/src/app/page.tsx" <<'EOF'
export default function Home() {
  return (
    <main style={{ padding: "40px", color: "#c8dff5" }}>
      <h1 style={{ fontFamily: "sans-serif", fontSize: "32px" }}>
        Poseidon OS — Online
      </h1>
      <p style={{ marginTop: "12px", color: "#7a9bc4" }}>
        Platform is operational. Replace this with your dashboard component.
      </p>
    </main>
  )
}
EOF

echo "Clean slate confirmed."
cd "${FRONTEND_DIR}"
npm install
echo "Install complete."

if [[ ${RUN_DEV} -eq 1 ]]; then
  echo "Starting Next dev server..."
  exec npm run dev
fi

echo "Run 'cd frontend && npm run dev' to verify locally."
