import { createHash } from "node:crypto"
import { promises as fs } from "node:fs"
import path from "node:path"
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib"
import type { SpearCase, StoredDocument } from "@/lib/poseidon-store"
import type { RouteDecision, VerifiedDestination } from "@/lib/trident/authorization"

type Certification = { reviewer_name: string; reviewer_role: string; reviewer_email?: string; certified_at: string; source_packet_artifact_id: string; source_packet_sha256: string; answers: Record<string, boolean> }
export type TridentHardPacketInput = { caseRecord: SpearCase; documents: StoredDocument[]; route: RouteDecision; destination: VerifiedDestination; payerRule: Record<string,unknown>; version: number; certification?: Certification }
const PAGE: [number,number] = [612,792]
const navy = rgb(.04,.12,.23), muted = rgb(.35,.42,.5), light = rgb(.94,.96,.98)
function sha(bytes: Buffer) { return createHash("sha256").update(bytes).digest("hex") }
function value(record: Record<string,unknown>, ...keys: string[]) { for (const key of keys) if (record[key] !== null && record[key] !== undefined && String(record[key]).trim()) return String(record[key]).trim(); return "Not documented" }
function list(candidate: unknown) { return Array.isArray(candidate) ? candidate.map(String).filter(Boolean) : typeof candidate === "string" ? candidate.split(/[\s,]+/).filter(Boolean) : [] }
function codes(record: SpearCase) { return list(record.final_hcpcs || record.operator_approved_hcpcs || record.trident_recommended_hcpcs || record.hcpcs) }
function diagnoses(record: SpearCase) { return list(record.final_icd || record.operator_approved_icd || record.trident_recommended_icd || record.icd) }
function wrap(line: string, font: PDFFont, size: number, width = 520) { const output: string[]=[]; let current=""; for (const word of line.split(/\s+/)) { const next=current?`${current} ${word}`:word; if (font.widthOfTextAtSize(next,size)<=width) current=next; else { if(current) output.push(current); current=word } } if(current) output.push(current); return output.length?output:[""] }
function header(page: PDFPage, bold: PDFFont, title: string, eyebrow: string) { const {height,width}=page.getSize(); page.drawRectangle({x:0,y:height-86,width,height:86,color:navy}); page.drawText(eyebrow.toUpperCase(),{x:42,y:height-34,size:9,font:bold,color:rgb(.55,.74,1)}); page.drawText(title,{x:42,y:height-62,size:19,font:bold,color:rgb(1,1,1)}) }
async function textDocument(title: string, eyebrow: string, lines: string[], small=false) { const doc=await PDFDocument.create(); const regular=await doc.embedFont(StandardFonts.Helvetica); const bold=await doc.embedFont(StandardFonts.HelveticaBold); const size=small?8.5:10, lineHeight=small?12:15; let page=doc.addPage(PAGE), y=676; header(page,bold,title,eyebrow); for(const source of lines){const heading=source.startsWith("## "), clean=heading?source.slice(3):source, font=heading?bold:regular, currentSize=heading?size+1.5:size, linesWrapped=wrap(clean,font,currentSize); if(y-linesWrapped.length*lineHeight<52){page=doc.addPage(PAGE);header(page,bold,`${title} (continued)`,eyebrow);y=676} if(heading)y-=5; for(const row of linesWrapped){page.drawText(row||" ",{x:46,y,size:currentSize,font,color:heading?navy:muted});y-=lineHeight}y-=heading?5:2} return doc }
async function append(target: PDFDocument, source: PDFDocument) { const pages=await target.copyPages(source,source.getPageIndices()); pages.forEach((page)=>target.addPage(page)) }
function docHash(document: StoredDocument) { return document.sha256 || (document.content_base64 ? sha(Buffer.from(document.content_base64,"base64")) : "bytes-unavailable") }
async function exhibit(label:string,title:string,documents:StoredDocument[],applicable=true){const cover=await textDocument(`${label} — ${title}`,"Evidence exhibit",documents.length?documents.flatMap((document)=>[`## ${document.filename}`,`Document ID: ${document.id}`,`SHA-256: ${docHash(document)}`,`Stored at: ${document.created_at}`]):[applicable?"Required evidence was not supplied.":"Not applicable for this procedural posture."],true);for(const document of documents){if(document.content_type!=="application/pdf"||!document.content_base64)continue;try{await append(cover,await PDFDocument.load(Buffer.from(document.content_base64,"base64"),{ignoreEncryption:false}))}catch{await append(cover,await textDocument(`${label} — attachment exception`,"Evidence exhibit",[`${document.filename} could not be merged.`,`Immutable source SHA-256: ${docHash(document)}`]))}}return cover}

export async function buildTridentHardPacket(input: TridentHardPacketInput) {
  const {caseRecord,documents,route,destination,payerRule,version,certification}=input
  const record=caseRecord as Record<string,unknown>, packetId=`TRIDENT-${caseRecord.id}-V${version}`, requested=codes(caseRecord), diagnosis=diagnoses(caseRecord)
  const specs=[
    {label:"Exhibit A",title:"Physician Order",kinds:["physician_order","signed_swo"],applicable:true,proves:"Ordering-provider intent, ordered item, and signature."},
    {label:"Exhibit B",title:"Clinical Notes",kinds:["clinical_notes"],applicable:true,proves:"Physician assessment, functional deficit, and treatment objective."},
    {label:"Exhibit C",title:"Diagnostics",kinds:["diagnostics","diagnostic_evidence"],applicable:true,proves:"Imaging, laboratory, or functional-assessment support."},
    {label:"Exhibit D",title:"Eligibility Evidence",kinds:["eligibility","eligibility_evidence"],applicable:true,proves:"Demographics, coverage, eligibility, and benefits verification."},
    {label:"Exhibit E",title:"Proof of Delivery",kinds:["pod","signed_pod"],applicable:route.route!=="prospective",proves:"Delivery evidence for retrospective, claims, appeal, or audit posture."},
  ]
  const exhibitDocuments=specs.map((spec)=>documents.filter((document)=>spec.kinds.includes(document.kind)))
  const exhibits=await Promise.all(specs.map((spec,index)=>exhibit(spec.label,spec.title,exhibitDocuments[index],spec.applicable)))
  const requirementMap=(payerRule.hcpcs_requirements && typeof payerRule.hcpcs_requirements==="object" ? payerRule.hcpcs_requirements : {}) as Record<string,unknown>
  const coverageRequirement=(hcpcs:string)=>String(requirementMap[hcpcs] || payerRule.documentation_requirement || `Apply the verified payer policy criteria for ${hcpcs}.`)
  const coreSections=[
    await textDocument(route.title,"StrykeFox Medical — SPEAR",[`## Packet control`,`Packet ID: ${packetId}`,`Case: ${caseRecord.id}`,`Order: ${caseRecord.order_id}`,`Version: ${version}`,`Patient: ${caseRecord.patient_name}`,`DOB: ${caseRecord.dob}`,`Member ID: ${caseRecord.member_id}`,`Payer: ${caseRecord.payer}`,`Destination: ${destination.channel.toUpperCase()} ${destination.destination}`,`Verified: ${destination.verified_at} by ${destination.verified_by}`]),
    await textDocument("TRIDENT Authorization Packet","Operational documentation intelligence",["TRIDENT evaluates completeness, traceability, payer-policy alignment, and routing. It does not make clinical decisions.",`Procedural posture: ${route.title}`,`Packet version: ${version}`,"Every conclusion must be grounded in cited evidence and reviewer-certified before transmission."]),
    await textDocument("Routing Determination","Procedural route",[`## ${route.title}`,`Route code: ${route.route}`,...route.basis,`Decision timestamp: ${route.decided_at}`,`Channel: ${destination.channel}`,`Verified destination: ${destination.destination}`,`Verification source: ${destination.source}`]),
    await textDocument("Case and Order Summary","Patient-facing identifiers",[`Patient: ${caseRecord.patient_name}`,`DOB: ${caseRecord.dob}`,`MRN: ${value(record,"mrn")}`,`Member ID: ${caseRecord.member_id}`,`Payer: ${caseRecord.payer}`,`Plan/product: ${value(record,"plan_product","payer_plan")}`,`State/jurisdiction: ${value(record,"state","jurisdiction")}`,`Provider: ${caseRecord.provider}`,`Provider NPI: ${caseRecord.npi}`,`Supplier/facility: ${value(record,"supplier_name","facility")}`,`Supplier NPI: ${value(record,"supplier_npi","facility_npi")}`,`Supplier TIN: ${value(record,"supplier_tin","facility_tin")}`,`Date of service: ${value(record,"date_of_service","dos","scheduled_dos")}`,`HCPCS: ${requested.join(", ")}`,`ICD-10: ${diagnosis.join(", ")}`]),
    await textDocument("Eligibility and Benefits","Validation",[`Eligibility: ${value(record,"eligibility_status")}`,`Verified at: ${value(record,"eligibility_verified_at")}`,`Source: ${value(record,"eligibility_source")}`,`Benefits: ${value(record,"benefit_verification_status")}`,`Verified at: ${value(record,"benefit_verified_at")}`,`Source: ${value(record,"benefit_source")}`]),
  ]
  const policy=await textDocument("Payer Policy Crosswalk","Policy control",requested.flatMap((hcpcs)=>[`## ${hcpcs}`,`Payer: ${caseRecord.payer}`,`Plan/product: ${value(record,"plan_product","payer_plan")}`,`State/jurisdiction: ${value(record,"state","jurisdiction")}`,`Applicable policy: ${value(payerRule,"policy_name","name")}`,`Version/effective date: ${value(payerRule,"policy_version","policy_effective_date")}`,`Benefit category: ${value(payerRule,"benefit_category")}`,`Documentation requirement: ${coverageRequirement(hcpcs)}`,`Physician-order requirement: ${value(payerRule,"physician_order_requirement")}`,`Medical-necessity requirement: ${value(payerRule,"medical_necessity_requirement")}`,`Source/reference: ${value(payerRule,"policy_source","policy_url")}`,`Verified at: ${value(payerRule,"policy_verified_at")}`,`Reviewer conclusion: pending authenticated certification.`]),true)
  type EvidenceIndexRow={label:string;pages:string;document_ids:string[];hashes:string[];proves:string;hcpcs:string[]}
  let evidence_index: EvidenceIndexRow[]=specs.map((spec,index)=>({label:`${spec.label} — ${spec.title}`,pages:"pending",document_ids:exhibitDocuments[index].map((document)=>document.id),hashes:exhibitDocuments[index].map(docHash),proves:spec.proves,hcpcs:requested}))
  let criteria_matrix: Array<{hcpcs:string;diagnosis:string;coverage_requirement:string;evidence:string;exhibit:string;page_location:string;status:"pass"|"deficiency"|"reviewer_needed"}>=[]
  let matrix=await textDocument("HCPCS Criteria Matrix","Evidence traceability",["Page mapping pending deterministic assembly."],true)
  let narrative=await textDocument("Item-Specific Medical Necessity Narratives","Record-grounded narrative",["Page mapping pending deterministic assembly."],true)
  let index=await textDocument("Evidence Index","Deterministic two-pass index",["Final page mapping pending."],true)
  for(let pass=0;pass<4;pass+=1){
    criteria_matrix=requested.map((hcpcs)=>{const mapped=evidence_index.filter((entry)=>entry.document_ids.length&&entry.label!=="Exhibit E — Proof of Delivery");const complete=mapped.length>=4&&![value(record,"functional_deficit"),value(record,"physician_assessment"),value(record,"treatment_objective"),value(record,"expected_clinical_benefit")].includes("Not documented");return{hcpcs,diagnosis:diagnosis.join(", ")||"Not documented",coverage_requirement:coverageRequirement(hcpcs),evidence:mapped.map((entry)=>`${entry.label}: ${entry.proves}`).join(" ")||"Missing",exhibit:mapped.map((entry)=>entry.label.split(" — ")[0]).join(", ")||"Missing",page_location:mapped.map((entry)=>entry.pages).join(", ")||"Missing",status:(!mapped.length?"deficiency":complete?"pass":"reviewer_needed") as "pass"|"deficiency"|"reviewer_needed"}})
    matrix=await textDocument("HCPCS Criteria Matrix","Evidence traceability",criteria_matrix.flatMap((row)=>[`## ${row.hcpcs} — ${row.status.replace(/_/g," ")}`,`Diagnosis: ${row.diagnosis}`,`Coverage requirement: ${row.coverage_requirement}`,`Evidence satisfying requirement: ${row.evidence}`,`Exhibit: ${row.exhibit}`,`Exact final packet page(s): ${row.page_location}`]),true)
    narrative=await textDocument("Item-Specific Medical Necessity Narratives","Record-grounded narrative",requested.flatMap((hcpcs)=>{const row=criteria_matrix.find((item)=>item.hcpcs===hcpcs);return[`## ${hcpcs}`,`Requested device or item: ${caseRecord.product || hcpcs} (${hcpcs}), ${caseRecord.laterality || "laterality not documented"}.`,`Diagnosis: ${diagnosis.join(", ")||"Not documented"}.`,`Functional deficit: ${value(record,"functional_deficit")}.`,`Physician assessment: ${value(record,"physician_assessment")}.`,`Treatment objective: ${value(record,"treatment_objective")}.`,`Expected clinical benefit: ${value(record,"expected_clinical_benefit")}.`,`Supporting exhibit and exact page(s): ${row?.exhibit||"Missing"}; ${row?.page_location||"Missing"}.`,`Reviewer status: ${row?.status.replace(/_/g," ")||"deficiency"}. This narrative contains only structured case facts and cited evidence.`]}),true)
    const prePages=[...coreSections,matrix,policy,narrative].reduce((sum,section)=>sum+section.getPageCount(),0)
    index=await textDocument("Evidence Index","Deterministic two-pass index",evidence_index.flatMap((entry)=>[`## ${entry.label} — pages ${entry.pages}`,`What this proves: ${entry.proves}`,`HCPCS/requirement supported: ${entry.hcpcs.join(", ")||"Not applicable"}`,`Document IDs: ${entry.document_ids.join(", ")||"None"}`,`SHA-256: ${entry.hashes.join(", ")||"Not applicable"}`]),true)
    let cursor=prePages+index.getPageCount()+1
    const next=specs.map((spec,specIndex)=>{const start=cursor,end=start+exhibits[specIndex].getPageCount()-1;cursor=end+1;return{label:`${spec.label} — ${spec.title}`,pages:start===end?String(start):`${start}-${end}`,document_ids:exhibitDocuments[specIndex].map((document)=>document.id),hashes:exhibitDocuments[specIndex].map(docHash),proves:spec.proves,hcpcs:requested}})
    if(JSON.stringify(next)===JSON.stringify(evidence_index))break
    evidence_index=next
  }
  index=await textDocument("Evidence Index","Deterministic two-pass index",evidence_index.flatMap((entry)=>[`## ${entry.label} — pages ${entry.pages}`,`What this proves: ${entry.proves}`,`HCPCS/requirement supported: ${entry.hcpcs.join(", ")||"Not applicable"}`,`Document IDs: ${entry.document_ids.join(", ")||"None"}`,`SHA-256: ${entry.hashes.join(", ")||"Not applicable"}`]),true)
  const sections=[...coreSections,matrix,policy,narrative]
  const certLines=certification?[`## Reviewer certification`,`Reviewer: ${certification.reviewer_name}`,`Role: ${certification.reviewer_role}`,`Email: ${certification.reviewer_email||"Not supplied"}`,`Certified at: ${certification.certified_at}`,`Source packet: ${certification.source_packet_artifact_id}`,`Source SHA-256: ${certification.source_packet_sha256}`,...Object.entries(certification.answers).map(([question,answer])=>`${question.replace(/_/g," ")}: ${answer?"YES":"NO"}`),"Reviewer certifies route, policy, destination, criteria, narrative, and evidence index were reviewed."]:["## Certification pending","This review copy is not eligible for transmission.","Certification creates a new immutable packet version with the completed certification page."]
  const cert=await textDocument("Reviewer Certification","Transmission gate",certLines,true), output=await PDFDocument.create()
  for(const section of sections)await append(output,section);await append(output,index);for(const item of exhibits)await append(output,item);await append(output,cert)
  output.setTitle(`${route.title} — ${caseRecord.patient_name}`);output.setSubject(`TRIDENT authorization packet ${packetId}`);output.setProducer("StrykeFox SPEAR / TRIDENT")
  const footer=await output.embedFont(StandardFonts.Helvetica),total=output.getPageCount();output.getPages().forEach((page,index)=>{const {width}=page.getSize();page.drawRectangle({x:0,y:0,width,height:34,color:light});page.drawText(`${packetId} • Page ${index+1} of ${total}`,{x:42,y:13,size:7.5,font:footer,color:muted})})
  try{const logo=await output.embedPng(await fs.readFile(path.join(process.cwd(),"public","images","spear-logo.png")));output.getPage(0).drawImage(logo,{x:512,y:700,width:54,height:54})}catch{}
  const bytes=Buffer.from(await output.save({useObjectStreams:false}));return{bytes,sha256:sha(bytes),page_count:total,version,title:route.title,evidence_index,criteria_matrix}
}
