/** Values for `PayerManual.parsedStatus`. */
export const MANUAL_PARSED_STATUS = {
  PENDING: "PENDING",
  PARSED: "PARSED",
  REVIEWED: "REVIEWED",
  FAILED: "FAILED",
} as const;

/** Persisted `ManualRequirement.requirementType` (manual-authoritative baseline). */
export const REQUIREMENT_TYPE = {
  REQUIRED_DOCUMENT: "REQUIRED_DOCUMENT",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  TIMING_RULE: "TIMING_RULE",
  RESTRICTION: "RESTRICTION",
  ESCALATION: "ESCALATION",
} as const;

/** Persisted `ManualRequirement.reviewState`. APPROVED is protected from automatic re-extract. */
export const MANUAL_REQUIREMENT_REVIEW_STATE = {
  AUTO_PENDING: "AUTO_PENDING",
  AUTO_ACCEPT: "AUTO_ACCEPT",
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export const MANUAL_EXTRACTION_SOURCE = {
  DETERMINISTIC: "DETERMINISTIC",
  LLM: "LLM",
} as const;

/** Confidence at or above this threshold (deterministic only) gets AUTO_ACCEPT + active. */
export const MANUAL_EXTRACTION_AUTO_ACCEPT_CONFIDENCE = 0.8;

/** Internal extractor labels before mapping to {@link REQUIREMENT_TYPE}. */
export const MANUAL_REQUIREMENT_CATEGORY = {
  REQUIRED_DOCUMENT: "REQUIRED_DOCUMENT",
  AUTHORIZATION_REQUIREMENT: "AUTHORIZATION_REQUIREMENT",
  DIAGNOSIS_DEVICE_RESTRICTION: "DIAGNOSIS_DEVICE_RESTRICTION",
  TIMING_RULE: "TIMING_RULE",
  ESCALATION: "ESCALATION",
  DOCUMENTATION_LANGUAGE: "DOCUMENTATION_LANGUAGE",
  SUBMISSION_LIMITATION: "SUBMISSION_LIMITATION",
} as const;

export const EXTRACTION_CONFIDENCE = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
} as const;

export function confidenceToFloat(tier: string): number {
  if (tier === EXTRACTION_CONFIDENCE.HIGH) return 0.9;
  if (tier === EXTRACTION_CONFIDENCE.MEDIUM) return 0.72;
  return 0.55;
}

export function mapCategoryToRequirementType(category: string): string {
  switch (category) {
    case MANUAL_REQUIREMENT_CATEGORY.AUTHORIZATION_REQUIREMENT:
      return REQUIREMENT_TYPE.AUTH_REQUIRED;
    case MANUAL_REQUIREMENT_CATEGORY.TIMING_RULE:
      return REQUIREMENT_TYPE.TIMING_RULE;
    case MANUAL_REQUIREMENT_CATEGORY.ESCALATION:
      return REQUIREMENT_TYPE.ESCALATION;
    case MANUAL_REQUIREMENT_CATEGORY.DIAGNOSIS_DEVICE_RESTRICTION:
    case MANUAL_REQUIREMENT_CATEGORY.DOCUMENTATION_LANGUAGE:
    case MANUAL_REQUIREMENT_CATEGORY.SUBMISSION_LIMITATION:
      return REQUIREMENT_TYPE.RESTRICTION;
    default:
      return REQUIREMENT_TYPE.REQUIRED_DOCUMENT;
  }
}

/** Governance queue + decisions */
export const GOVERNANCE_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  IMPLEMENTED: "IMPLEMENTED",
  SUPERSEDED: "SUPERSEDED",
} as const;

export const GOVERNANCE_RECOMMENDATION_TYPE = {
  PROMOTE_PLAYBOOK: "PROMOTE_PLAYBOOK",
  REVISE_PLAYBOOK: "REVISE_PLAYBOOK",
  RETIRE_PLAYBOOK: "RETIRE_PLAYBOOK",
  CREATE_RULE: "CREATE_RULE",
  ADJUST_SCORE_WEIGHT: "ADJUST_SCORE_WEIGHT",
} as const;

export const GOVERNANCE_TARGET_TYPE = {
  PLAYBOOK: "PLAYBOOK",
  RULE: "RULE",
  SCORE_PROFILE: "SCORE_PROFILE",
} as const;

export const GOVERNANCE_DECISION_VALUE = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

/** Learned suggestion lifecycle */
export const LEARNED_SUGGESTION_STATUS = {
  DRAFT: "DRAFT",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  APPLIED: "APPLIED",
} as const;

export const LEARNED_SUGGESTION_TYPE = {
  SCORE_WEIGHT: "SCORE_WEIGHT",
  DOC_REQUIREMENT_HINT: "DOC_REQUIREMENT_HINT",
  PLAYBOOK_REVISION: "PLAYBOOK_REVISION",
  ROUTING_HINT: "ROUTING_HINT",
} as const;
