import { NextRequest, NextResponse } from "next/server";
import { getRequiredEnv, getServiceBaseUrl } from "@/lib/runtime-config";
import { getSafeServerSession } from "@/lib/auth";

const SINCH_FAX_BASE = "https://fax.api.sinch.com/v3";

interface FaxPayload {
  recipientFax: string;
  senderFax?: string;
  patientId?: string;
  orderId?: string;
  recipientName?: string;
  recipientFacility?: string;
  senderName?: string;
  senderFacility?: string;
  patientName: string;
  patientDOB?: string;
  patientMRN?: string;
  recordTypes: string[];
  dateRange?: string;
  customStart?: string;
  customEnd?: string;
  urgency: string;
  notes?: string;
  authorizationOnFile?: boolean;
  releaseSignedBy?: string;
  releaseSignerRelationship?: string;
  releaseSignedAt?: string;
  releasePurpose?: string;
  releaseAuthorizedBy?: string;
  releaseAttachmentLabel?: string;
}

function escapeHtml(value: string | undefined): string {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildAuthorizationHtml(payload: FaxPayload): string {
  const signedBy = payload.releaseSignedBy || payload.patientName;
  const relationship = payload.releaseSignerRelationship || "Self";
  const signedAt = payload.releaseSignedAt || new Date().toISOString().slice(0, 10);
  const purpose = payload.releasePurpose || payload.notes || "Continuity of care";
  const authorizedBy = payload.releaseAuthorizedBy || "Patient-authorized release";
  const recordList = payload.recordTypes.length
    ? payload.recordTypes.map((record) => `<li>${escapeHtml(record)}</li>`).join("")
    : "<li>All available medical records reasonably necessary for treatment and care coordination.</li>";

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: Arial, sans-serif; margin: 36px; color: #111827; line-height: 1.5; }
  h1 { font-size: 20px; margin-bottom: 6px; }
  h2 { font-size: 13px; margin: 20px 0 8px; text-transform: uppercase; letter-spacing: 1px; color: #0f766e; }
  .meta { color: #475569; font-size: 12px; margin-bottom: 18px; }
  .box { border: 1px solid #cbd5e1; border-radius: 10px; padding: 14px 16px; margin-bottom: 14px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .label { font-size: 10px; text-transform: uppercase; color: #64748b; }
  .value { font-size: 13px; font-weight: 600; }
  ul { margin: 8px 0 0 18px; }
  .fine-print { font-size: 10px; color: #475569; margin-top: 18px; }
</style></head>
<body>
  <h1>Authorization for Release of Protected Health Information</h1>
  <p class="meta">Generated by StrykeFox Medical Platform for fax release documentation under 45 CFR 164.508.</p>

  <div class="box grid">
    <div><div class="label">Patient</div><div class="value">${escapeHtml(payload.patientName)}</div></div>
    <div><div class="label">Date of Birth</div><div class="value">${escapeHtml(payload.patientDOB || "Not provided")}</div></div>
    <div><div class="label">MRN / Account</div><div class="value">${escapeHtml(payload.patientMRN || "Not provided")}</div></div>
    <div><div class="label">Recipient</div><div class="value">${escapeHtml(payload.recipientFacility || payload.recipientName || payload.recipientFax)}</div></div>
  </div>

  <div class="box">
    <div class="label">Information Authorized for Release</div>
    <ul>${recordList}</ul>
    <p><strong>Date range:</strong> ${escapeHtml(
      payload.dateRange === "Custom Date Range"
        ? `${payload.customStart || "N/A"} to ${payload.customEnd || "N/A"}`
        : payload.dateRange || "All Available Records",
    )}</p>
    <p><strong>Purpose:</strong> ${escapeHtml(purpose)}</p>
    <p><strong>Authorized by:</strong> ${escapeHtml(authorizedBy)}</p>
  </div>

  <div class="box grid">
    <div><div class="label">Signed By</div><div class="value">${escapeHtml(signedBy)}</div></div>
    <div><div class="label">Relationship</div><div class="value">${escapeHtml(relationship)}</div></div>
    <div><div class="label">Signed Date</div><div class="value">${escapeHtml(signedAt)}</div></div>
    <div><div class="label">Authorization Confirmed</div><div class="value">${payload.authorizationOnFile ? "Yes" : "No"}</div></div>
  </div>

  <p class="fine-print">
    This authorization may be revoked in writing except to the extent action has already been taken in reliance on it.
    The requesting party certifies that the patient or the patient&apos;s legal representative executed this authorization
    and that only the minimum necessary information for the stated purpose is being disclosed.
  </p>
</body>
</html>`;
}

function buildCoverPageHtml(payload: FaxPayload): string {
  const recordList = payload.recordTypes.length
    ? payload.recordTypes.map((r) => `<li>${r}</li>`).join("")
    : "<li>All Available Records</li>";

  const dateInfo =
    payload.dateRange === "Custom Date Range"
      ? `${payload.customStart || "N/A"} to ${payload.customEnd || "N/A"}`
      : payload.dateRange || "All Available Records";

  const urgencyLabel: Record<string, string> = {
    routine: "Routine (5-10 business days)",
    urgent: "URGENT (24-48 hours)",
    stat: "STAT - IMMEDIATE",
  };

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #1e293b; }
  .header { border-bottom: 3px solid #0f766e; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 24px; font-weight: bold; color: #0f766e; }
  .subtitle { font-size: 11px; color: #64748b; letter-spacing: 2px; }
  .grid { display: flex; gap: 32px; margin-bottom: 24px; }
  .col { flex: 1; }
  .section { margin-bottom: 20px; }
  .section-title { font-size: 11px; font-weight: bold; color: #0f766e; text-transform: uppercase;
    letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-bottom: 8px; }
  .field { margin-bottom: 6px; }
  .label { font-size: 10px; color: #94a3b8; text-transform: uppercase; }
  .value { font-size: 13px; font-weight: 600; }
  .urgency-stat { color: #dc2626; font-weight: bold; font-size: 14px; }
  .urgency-urgent { color: #d97706; font-weight: bold; }
  .records-list { list-style: none; padding: 0; }
  .records-list li { padding: 4px 0; font-size: 12px; }
  .records-list li::before { content: "\\2713  "; color: #0f766e; font-weight: bold; }
  .hipaa { margin-top: 32px; padding: 16px; background: #fffbeb; border: 1px solid #fbbf24;
    font-size: 9px; line-height: 1.5; color: #92400e; }
  .hipaa-title { font-weight: bold; font-size: 10px; margin-bottom: 4px; }
  .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #94a3b8; }
</style></head>
<body>
  <div class="header">
    <div class="logo">STRYKEFOX</div>
    <div class="subtitle">MEDICAL RECORDS REQUEST</div>
  </div>

  <div class="grid">
    <div class="col">
      <div class="section">
        <div class="section-title">From</div>
        <div class="field"><span class="label">Name: </span><span class="value">${escapeHtml(payload.senderName || "N/A")}</span></div>
        <div class="field"><span class="label">Facility: </span><span class="value">${escapeHtml(payload.senderFacility || "N/A")}</span></div>
        <div class="field"><span class="label">Fax: </span><span class="value">${escapeHtml(payload.senderFax || "N/A")}</span></div>
      </div>
    </div>
    <div class="col">
      <div class="section">
        <div class="section-title">To</div>
        <div class="field"><span class="label">Name: </span><span class="value">${escapeHtml(payload.recipientName || "N/A")}</span></div>
        <div class="field"><span class="label">Facility: </span><span class="value">${escapeHtml(payload.recipientFacility || "N/A")}</span></div>
        <div class="field"><span class="label">Fax: </span><span class="value">${escapeHtml(payload.recipientFax)}</span></div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Patient Information</div>
    <div class="field"><span class="label">Patient Name: </span><span class="value">${escapeHtml(payload.patientName)}</span></div>
    <div class="field"><span class="label">Date of Birth: </span><span class="value">${escapeHtml(payload.patientDOB || "N/A")}</span></div>
    <div class="field"><span class="label">MRN / Account #: </span><span class="value">${escapeHtml(payload.patientMRN || "N/A")}</span></div>
  </div>

  <div class="section">
    <div class="section-title">Records Requested</div>
    <ul class="records-list">${recordList}</ul>
    <div class="field" style="margin-top:8px"><span class="label">Date Range: </span><span class="value">${escapeHtml(dateInfo)}</span></div>
    <div class="field"><span class="label">Urgency: </span><span class="value ${payload.urgency === "stat" ? "urgency-stat" : payload.urgency === "urgent" ? "urgency-urgent" : ""}">${escapeHtml(urgencyLabel[payload.urgency] || payload.urgency)}</span></div>
    ${payload.notes ? `<div class="field" style="margin-top:8px"><span class="label">Notes: </span><span class="value">${escapeHtml(payload.notes)}</span></div>` : ""}
    <div class="field" style="margin-top:8px"><span class="label">Release Signed By: </span><span class="value">${escapeHtml(payload.releaseSignedBy || payload.patientName)}</span></div>
    <div class="field"><span class="label">Signed Date: </span><span class="value">${escapeHtml(payload.releaseSignedAt || "Not provided")}</span></div>
  </div>

  <div class="hipaa">
    <div class="hipaa-title">CONFIDENTIALITY NOTICE</div>
    This facsimile transmission contains confidential information that is legally privileged.
    This information is intended only for the use of the individual or entity named above.
    The authorized recipient of this information is prohibited from disclosing this information
    to any other party unless required to do so by law or regulation and is required to destroy
    the information after its stated need has been fulfilled. If you are not the intended recipient,
    you are hereby notified that any disclosure, copying, distribution, or action taken in reliance
    on the contents of these documents is STRICTLY PROHIBITED. If you have received this fax in error,
    please notify the sender immediately by telephone to arrange for the return of the original documents.
  </div>

  <div class="footer">
    &copy; ${new Date().getFullYear()} StrykeFox Medical Platform &mdash; HIPAA Compliant &mdash; 45 CFR &sect;164
  </div>
</body>
</html>`;
}

function normalizeFaxNumber(num: string): string {
  const digits = num.replace(/\D/g, "");
  if (digits.length === 10) return `+1${digits}`;
  if (digits.length === 11 && digits.startsWith("1")) return `+${digits}`;
  return `+${digits}`;
}

function tryNormalizeFaxNumber(num: string | undefined): string | null {
  const digits = String(num || "").replace(/\D/g, "");
  if (digits.length < 10) return null;
  return normalizeFaxNumber(digits);
}

export async function POST(req: NextRequest) {
  const session = await getSafeServerSession();
  if (!session?.user?.accessToken) {
    return NextResponse.json(
      { error: "Your session expired. Please sign in again and resend the fax." },
      { status: 401 },
    );
  }

  // Sinch credentials
  let SINCH_PROJECT_ID = "";
  let SINCH_KEY_ID = "";
  let SINCH_KEY_SECRET = "";
  let coreApiUrl = "";
  try {
    SINCH_PROJECT_ID = getRequiredEnv("SINCH_PROJECT_ID");
    SINCH_KEY_ID = getRequiredEnv("SINCH_KEY_ID");
    SINCH_KEY_SECRET = getRequiredEnv("SINCH_KEY_SECRET");
    coreApiUrl = getServiceBaseUrl("POSEIDON_API_URL");
  } catch {
    return NextResponse.json(
      { error: "Fax service is not configured for production-safe execution." },
      { status: 503 },
    );
  }

  let payload: FaxPayload;
  let attachmentBuffers: { name: string; buffer: Buffer; type: string }[] = [];

  const contentType = req.headers.get("content-type") || "";

  if (contentType.includes("multipart/form-data")) {
    const body = await req.formData();
    const jsonStr = body.get("payload") as string;
    if (!jsonStr) {
      return NextResponse.json(
        { error: "Missing payload field" },
        { status: 400 }
      );
    }
    payload = JSON.parse(jsonStr);

    const files = body.getAll("attachments");
    for (const file of files) {
      if (file instanceof Blob) {
        const buf = Buffer.from(await file.arrayBuffer());
        attachmentBuffers.push({
          name: (file as File).name || "attachment",
          buffer: buf,
          type: file.type || "application/pdf",
        });
      }
    }
  } else {
    payload = await req.json();
  }

  if (!payload.recipientFax || !payload.patientName) {
    return NextResponse.json(
      { error: "recipientFax and patientName are required" },
      { status: 400 }
    );
  }
  if (!payload.authorizationOnFile) {
    return NextResponse.json(
      { error: "Patient authorization confirmation is required before sending a records fax." },
      { status: 400 }
    );
  }
  if (!payload.releaseSignedBy?.trim() || !payload.releaseSignedAt?.trim()) {
    return NextResponse.json(
      { error: "Patient-executed release name and signature date are required." },
      { status: 400 }
    );
  }

  const coverHtml = buildCoverPageHtml(payload);
  const authorizationHtml = buildAuthorizationHtml(payload);
  const toNumber = normalizeFaxNumber(payload.recipientFax);

  // Build Sinch Fax API multipart request
  const sinchBody = new FormData();
  sinchBody.append("to", toNumber);

  const fromNumber =
    tryNormalizeFaxNumber(process.env.SINCH_FROM_NUMBER) ||
    tryNormalizeFaxNumber(payload.senderFax);
  if (fromNumber) {
    sinchBody.append("from", fromNumber);
  }

  // Header text appears at the top of each fax page
  sinchBody.append(
    "headerText",
    `StrykeFox Medical | ${payload.urgency === "stat" ? "STAT" : payload.urgency === "urgent" ? "URGENT" : "Routine"} | ${payload.patientName}`
  );

  // Only register a callback if the webhook side is configured to accept it.
  const callbackBase = process.env.NEXTAUTH_URL?.trim().replace(/\/$/, "") || "";
  const hasWebhookConfig = Boolean(
    callbackBase &&
    process.env.SINCH_WEBHOOK_SECRET?.trim() &&
    process.env.INTERNAL_API_KEY?.trim(),
  );
  if (hasWebhookConfig) {
    sinchBody.append("callbackUrl", `${callbackBase}/api/fax/inbound`);
    sinchBody.append("callbackUrlContentType", "application/json");
  }

  // Attach cover page as HTML file
  const coverBlob = new Blob([coverHtml], { type: "text/html" });
  sinchBody.append("file", coverBlob, "cover_page.html");
  const authorizationBlob = new Blob([authorizationHtml], { type: "text/html" });
  sinchBody.append(
    "file",
    authorizationBlob,
    `${(payload.releaseAttachmentLabel || "patient_release_authorization").replace(/[^a-zA-Z0-9._-]+/g, "_")}.html`
  );

  // Attach uploaded files
  for (const att of attachmentBuffers) {
    const blob = new Blob([new Uint8Array(att.buffer)], { type: att.type });
    sinchBody.append("file", blob, att.name);
  }

  // Basic auth: key_id:key_secret
  const basicAuth = Buffer.from(`${SINCH_KEY_ID}:${SINCH_KEY_SECRET}`).toString(
    "base64"
  );

  try {
    const faxRes = await fetch(
      `${SINCH_FAX_BASE}/projects/${SINCH_PROJECT_ID}/faxes`,
      {
        method: "POST",
        headers: {
          Authorization: `Basic ${basicAuth}`,
        },
        body: sinchBody,
      }
    );

    const faxData = await faxRes.json().catch(() => ({}));

    if (!faxRes.ok) {
      const sinchDetail =
        Array.isArray(faxData?.details) && faxData.details.length
          ? faxData.details
              .flatMap((detail: { message?: string; fieldViolations?: { field?: string; description?: string }[] }) => {
                const violations = Array.isArray(detail?.fieldViolations)
                  ? detail.fieldViolations
                      .map((violation) =>
                        violation?.field && violation?.description
                          ? `${violation.field}: ${violation.description}`
                          : violation?.description || violation?.field || "",
                      )
                      .filter(Boolean)
                  : [];
                if (violations.length) return violations;
                return detail?.message ? [detail.message] : [];
              })
              .join(" | ")
          : typeof faxData?.message === "string"
            ? faxData.message
            : undefined;

      console.error("Sinch fax send failed", {
        status: faxRes.status,
        detail: sinchDetail,
        toNumber,
        fromNumber,
        patientName: payload.patientName,
      });

      return NextResponse.json(
        {
          error: "Fax transmission failed",
          sinchStatus: faxRes.status,
          detail: sinchDetail,
        },
        { status: 502 }
      );
    }

    // Log to database via core service
    const logPayload = {
      direction: "outbound",
      fax_number: toNumber,
      facility: payload.recipientFacility || "",
      patient_name: payload.patientName,
      patient_dob: payload.patientDOB || null,
      patient_mrn: payload.patientMRN || null,
      patient_id: payload.patientId || null,
      order_id: payload.orderId || null,
      record_types: payload.recordTypes,
      urgency: payload.urgency,
      status: "sent",
      pages: 2 + attachmentBuffers.length,
      service: "sinch",
      sinch_fax_id: faxData.id || null,
      sent_by: session.user.email || "unknown",
      release_metadata: {
        authorization_on_file: Boolean(payload.authorizationOnFile),
        signed_by: payload.releaseSignedBy || payload.patientName,
        signer_relationship: payload.releaseSignerRelationship || "Self",
        signed_at: payload.releaseSignedAt || null,
        purpose: payload.releasePurpose || payload.notes || null,
        authorized_by: payload.releaseAuthorizedBy || null,
      },
    };

    // Fire-and-forget log to core
    fetch(`${coreApiUrl}/fax/log`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${session.user.accessToken}`,
      },
      body: JSON.stringify(logPayload),
    }).catch(() => {
      // Log failure is non-critical
    });

    return NextResponse.json({
      success: true,
      faxId: faxData.id,
      to: toNumber,
      pages: 2 + attachmentBuffers.length,
      status: faxData.status || "queued",
      timestamp: new Date().toISOString(),
      ...logPayload,
    });
  } catch (error) {
    console.error("Sinch fax transport error", {
      toNumber,
      patientName: payload.patientName,
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json(
      { error: "Unable to reach Sinch fax service" },
      { status: 502 }
    );
  }
}
